services:
  nt-solutions-front1:
    image: ${PROJECT_NAME}-${ENV}
    container_name: ${PROJECT_NAME}-${ENV}
    build:
      context: ../..
      dockerfile: ./environment/Dockerfile
      target: ${TARGET}
    ports:
      - "3000:3000"
    networks:
      - ${PROJECT_NAME}-network

networks:
  nt-solutions-front1-network:
    driver: bridge
    name: nt-solutions-front1-network